name: pa_mobile
description: Mobile Croix Rouge
version: 1.0.3+202308061
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash.png"
  android: true
  ios: true

dependencies:
  table_calendar: ^3.0.9
  bloc: ^8.1.1
  flutter_native_splash: ^2.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  http: ^1.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^8.0.0
  form_field_validator: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/croix-rouge.png"
  min_sdk_android: 18
