name: CI

on:
  push:
    branches:
      - master
      - dev
      - 'features/**'
      - 'fix/**'
  pull_request:
    branches:
      - master
      - dev
      - 'features/**'
      - 'fix/**'

jobs:
  checkout:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  clean:
    needs: checkout
    runs-on: self-hosted
    steps:
      - name: Clean
        run: flutter clean

  install:
    needs: clean
    runs-on: self-hosted
    steps:
      - name: Install dependencies
        run: flutter pub get
      - name: Copy properties
        run: cp /root/pa-cxr/key/key.properties ./android/app/.

  build:
    needs: install
    runs-on: self-hosted
    steps:
      - name: Build
        env:
          ANDROID_KEYSTORE_PATH: ${{ secrets.ANDROID_KEYSTORE_PATH }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
        run: flutter build apk --release --flavor production

  tests:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Tests
        run: flutter test

  security-scan:
    needs: tests
    runs-on: self-hosted
    steps:
      - name: Run MobSF Analysis
        uses: fundacaocerti/mobsf-action@v1.7.1
        env:
          INPUT_FILE_NAME: build/app/outputs/flutter-apk/app-production-release.apk
          SCAN_TYPE: apk
          OUTPUT_FILE_NAME: mobsf-report

      - name: Upload MobSF Analysis PDF Result
        uses: actions/upload-artifact@v2
        with:
          name: mobsf-report.pdf
          path: mobsf-report.pdf

      - name: Upload MobSF Analysis JSON Result
        uses: actions/upload-artifact@v2
        with:
          name: mobsf-report.json
          path: mobsf-report.json
