name: CI

on:
  push:
    branches:
      - master
      - dev
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - master
      - dev
      - 'feature/**'
      - 'fix/**'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.18.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter build apk --release

      - name: Tests
        run: flutter test
