name: CI

on:
  push:
    branches:
      - master
      - dev
      - 'features/**'
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - master
      - dev
      - 'features/**'
      - 'feature/**'
      - 'fix/**'

jobs:
  checkout:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  clean:
    needs: checkout
    runs-on: self-hosted
    steps:
      - name: Clean
        run: flutter clean

  install:
    needs: clean
    runs-on: self-hosted
    steps:
      - name: Install dependencies
        run: flutter pub get
      - name: Copy properties
        run: cp /root/pa-cxr/key/key.properties ./android/app/.

  build:
    needs: install
    runs-on: self-hosted
    steps:
      - name: Build
        env:
          ANDROID_KEYSTORE_PATH: ${{ secrets.ANDROID_KEYSTORE_PATH }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
        run: flutter build apk --release

  tests:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Tests
        run: flutter test

  security-scan:
    needs: tests
    runs-on: self-hosted
    steps:
      - name: Prepare file hierarchy
        run: |
          mkdir -p target
          cp build/app/outputs/flutter-apk/app-release.apk /tmp/.

      - name: Checkout repository mobsf-ci
        uses: actions/checkout@v2
        with:
          repository: Soluto/mobsf-ci

      - name: Run MobSF Analysis
        env:
          TARGET_PATH: 'target/app-release.apk'
        run: |
          mkdir target
          cp /tmp/app-release.apk ./target/.
          cp ~/pa-cxr/scan.rb ./scan/scan.rb
          docker-compose up --build --exit-code-from scan

      - name: Upload report
        run: cp output/report.pdf ~/pa-cxr/prod/mobile/.