name: CI

on:
  push:
    branches:
      - master
      - dev
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches:
      - master
      - dev
      - 'feature/**'
      - 'fix/**'

jobs:
  checkout:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  install:
    needs: checkout
    runs-on: self-hosted
    steps:
      - name: Install dependencies
        run: flutter pub get

  build:
    needs: install
    runs-on: self-hosted
    steps:
      - name: Build
        run: flutter build apk --release

  tests:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Tests
        run: flutter test
